services:
  - type: web
    name: banking-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: "mongodb+srv://mouhamedNdiaye:Fessel_2025@banking-platform.srkvxx7.mongodb.net/"       # Mets ta MongoDB URI dans le dashboard Render
      - key: JWT_SECRET
        value: "FE8C759E5E69ABBF5DEAE67D9783B"       # Mets ton secret JWT dans le dashboard Render
      - key: PORT
        value: 5000
